name: CI

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
    schedule:
        - cron: '42 2 * * *'

jobs:
  test-code:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.30'
#          - '5.32'
#          - 'latest'
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Checkout CPAN Dashboard
        uses: actions/checkout@v2
        with:
          repository: davorg/dashboard
          path: dashboard

      - name: Regular tests
        run: |
            cpanm --installdeps --notest .
            perl Makefile.PL
            make
            make test

      - name: Release tests
        env:
          RELEASE_TESTING: 1
        run: |
            cpanm --installdeps --notest .
            cpanm --notest Test::Version
            perl Makefile.PL
            make
            make test

      - name: Create pages
        if: ${{ matrix.perl-version == '5.30' && github.event_name != 'pull_request' }}
        run: |
            perl -Ilib bin/cpan-digger --version
            perl -Ilib bin/cpan-digger --recent 150 --vcs --sleep 2 --html docs

      - name: Commit new page
        run: |
            GIT_STATUS=$(git status --porcelain)
            echo $GIT_STATUS
            git config --global user.name 'Gabor Szabo'
            git config --global user.email 'gabor@szabgab.com'
            git add docs/
            if [ "$GIT_STATUS" != "" ]; then git commit -m "Automated Web page generation"; fi
            if [ "$GIT_STATUS" != "" ]; then git push; fi

