name: CI

on:
    push:
    pull_request:
    schedule:
        - cron: '42 2 * * *'

jobs:
  test-code:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.36'
#          - '5.32'
#          - 'latest'
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Checkout CPAN Dashboard
        uses: actions/checkout@v3
        with:
          repository: davorg/dashboard
          path: dashboard

      - name: Install dependencies
        run: |
            cpanm --installdeps --notest .

      - name: Show Errors on Ubuntu
        if:  ${{ failure() && matrix.runner == 'ubuntu-latest' }}
        run: |
           cat /home/runner/.cpanm/work/*/build.log

      - name: Regular tests
        run: |
            perl Makefile.PL
            make
            make test

      - name: Release tests
        env:
          RELEASE_TESTING: 1
        run: |
            cpanm --installdeps --notest .
            cpanm --notest Test::Version
            perl Makefile.PL
            make
            make test

      - name: Create pages
        if: ${{ matrix.perl-version == '5.36' && github.event_name != 'pull_request' }}
        run: |
            perl -Ilib bin/cpan-digger --version
            perl -Ilib bin/cpan-digger --recent 150 --vcs --sleep 2 --html docs
            perl bin/generate.pl 1000

      - name: Commit new page
        run: |
            set -x
            git config --global --add safe.directory /__w/CPAN-Digger/CPAN-Digger
            GIT_STATUS=$(git status --porcelain)
            echo $GIT_STATUS
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add docs/
            if [ "$GIT_STATUS" != "" ]; then git commit -m "Automated Web page generation"; fi
            if [ "$GIT_STATUS" != "" ]; then git push; fi

