name: CI

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
    schedule:
        - cron: '42 2 * * *'

jobs:
  test-code:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.30'
#          - '5.32'
#          - 'latest'
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Regular tests
        run: |
            cpanm --installdeps --notest .
            perl Makefile.PL
            make
            make test

      - name: Release tests
        env:
          RELEASE_TESTING: 1
        run: |
            cpanm --installdeps --notest .
            cpanm --notest Test::Version
            perl Makefile.PL
            make
            make test

      - name: Create pages
        if: ${{ github.event_name == 'schedule' && matrix.perl-version == '5.30' }}
        run: |
            perl -Ilib bin/cpan-digger --version
            perl -Ilib bin/cpan-digger --recent 100 --vcs --sleep 2 --html docs

            git config --global user.name 'Gabor Szabo'
            git config --global user.email 'szabgab@users.noreply.github.com'
            git commit -am "Automated Web page generation"
            git push

