name: Create HTML page

on:
    schedule:
        - cron: '*/5 * * * *'

jobs:
  web-page:
    runs-on: ubuntu-latest
    needs: test-code
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.30'
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Create pages
        run: |
            perl bin/cpan-digger --version

